name: Lint and test
on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependancies
        run: uv sync
      - name: Linter
        run: uv run ruff check
      - name: Formatter
        run: uv run ruff format --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          enable-cache: "true"
          cache-dependancy-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependancies
        run: uv sync
      - name: Test
        run: uv run pytest
